### PR TITLE
feat: add `biome`

### PR DESCRIPTION
**Pull request by roushou**
**What changed? Why?**

This PR replaces Prettier with [biome](https://biomejs.dev)

Some benefits:
- It's fast
- It's very fast
- Good defaults and extensible
- Handles formatting, linting, organizing imports (sort lines, sort inside curly braces...), sorting tailwind classes...
- Many more

Ran a quick benchmark.
- Prettier: 9s
- Biome: 500ms

| Biome      | Prettier |
| ----------- | ----------- |
| <video src="https://github.com/coinbase/onchainkit/assets/155655425/cb7d754e-8051-4c86-baeb-80fa579b9ad4" /> | <video src="https://github.com/coinbase/onchainkit/assets/155655425/5ac8d5ca-7219-4b51-b9fe-dec7c385cf29" /> |

**Notes to reviewers**

If needed there are plugins for editors https://biomejs.dev/guides/integrate-in-editor/

Depending on the point of view, the drawback is that it doesn't support `md` and `mdx` files.

I already ran formatting, linting and checking so that's why the big changes.

I also updated the `ci` which now throw errors. And I believe this is actually fair.

**How has it been tested?**

Check commit messages

### CODE REVIEW

**Comment by Zizzamia** [comment]
Tempted... let think on this

**Comment by roushou** [comment]
Little caveat to sorting Tailwind classes, it's part of their nursery to it has to be run using the `--unsafe` flag when linting which transforms single quotes in JSX into double quotes. It's fixable with a quick `format` or `check` right after.

**Comment by Zizzamia** [comment]
I think before being tempted to get more speed, would love your help in getting fix some of the linting.

I see some good linting missing in our current setup, and would love to get those, as it will help speed a lot code reviews.

**Comment by Zizzamia** [comment]
Btw @roushou, we really appreciate your help. What's your Twitter or Warpcast?

**Comment by roushou** [comment]
> Btw @roushou, we really appreciate your help. What's your Twitter or Warpcast?

Happy to help :+1: 

https://x.com/roushou_
https://warpcast.com/roushou

I started doing short posts and videos about the little PR I'm doing.

**Comment by roushou** [comment]
> I think before being tempted to get more speed, would love your help in getting fix some of the linting.
> 
> I see some good linting missing in our current setup, and would love to get those, as it will help speed a lot code reviews.

I updated the biome config to match the prettier config.

Which linting rules are you looking for? I only see eslint in the `framegear` package, not for the whole repository. It also uses Next for linting so it would be better to let it this way.

**Comment by roushou** [comment]
Not sure why tests are failing

https://github.com/coinbase/onchainkit/actions/runs/9413890436/job/25931609772?pr=469#step:5:22

**Comment by roushou** [comment]
Ok tests were failing because the `@js-environment jsdom` annotations need to be on top of the file. Something to keep in mind when organizing imports. A simple trick is add a line between the annotation and imports.

**Comment by roushou** [comment]
Fixed some linting issues @Zizzamia 

Here's a summary of what's left to fix.

image

All workflows pass except the one checking the formatting and linting. I think it's fine to use the the `Check` workflow as an indicator instead of a requirement.

What do you think of fixing the linting errors in separate PRs? This way we don't break existing logic.

**Comment by kyhyco** [comment]
Working on TokenKit + SwapKit for release. I can help afterwards :)

Thank you so much for your continued efforts! You are rocking it!

**Comment by kyhyco** [comment]
Is it possible to loosen some rules and tighten them as we go?

**Comment by Zizzamia** [comment]
Let me make a different plan here. Where we have `biome` as the main solution, but more a side tool for now.

So just add in the package.json, something like `yarn format:biome`, and start small.

The reason is because I do not quite trust `biome` yet, and for a project like OnchainKit any major changes, I want to give it the time to try it and see how it evolves.

so to recap:
- we are not deprecating what we have
- we are only starting with format for now
- we are only starting by adding a new script called `yarn format:biome`

**Comment by roushou** [comment]
@kyhyco Up to you to decide which rules you want to enforce. The documentation is available here https://biomejs.dev/linter/. But if you intend to enforce them later, you would be better off letting them enabled. It makes sense to use the CI as an indicator.

There is also a schema definition in the biome config file so you can use your LSP for completion. https://github.com/coinbase/onchainkit/pull/469/files#diff-2bc8a1f5e9380d5a187a4e90f11b4dd36c3abad6aea44c84be354a4f44cdec55R2

@Zizzamia I added back `prettier` and updated `package.json` https://github.com/coinbase/onchainkit/pull/469/commits/8e78948019d0c3d7583ab4ad91411a43ccc83c32 but not the workflow so it's explicit that some fixes need to be done.

**Comment by Zizzamia** [comment]
Just because this is a big PR, and I want to review everything carefully. Can we just ship `"format:biome": "biome format --write .",` in the package.json and ofcourse the biome configuration.

So that we can get that in, right away, and than work our way towards the rest.

Sorry I like incremental things, as they are easier to core review.

**Comment by roushou** [comment]
Closing in favor of https://github.com/coinbase/onchainkit/pull/497

**Pull request closed without merging**
