### PR TITLE
fix: revert "use client"

### PR DESCRIPTION
**Pull request by kyhyco**
**What changed? Why?**
ock bundles are in correctly compiled with `use client` #684

**Notes to reviewers**
we will unblock folks and allow a PR that handles this properly

**How has it been tested?**

### CODE REVIEW

**Comment by roushou** [comment]
Curious to know what was the issue @kyhyco

**Comment by roushou** [comment]
Ah nvm, just saw the linked issue

**Comment by kyhyco** [comment]
With `use client`, `yarn build` gave a warning previously that we previously missed.

**Comment by roushou** [comment]
Give a look at https://github.com/egoist/tsup

**Pull request merged**
